vim.g.mapleader = ' '
vim.g.maplocalleader = ' '
vim.opt.ignorecase = true
vim.opt.cursorline = true
vim.opt.smartcase = true
vim.opt.nu = true
vim.opt.relativenumber = true
vim.opt.tabstop = 4
vim.opt.softtabstop = 4
vim.opt.shiftwidth = 4
vim.opt.expandtab = true
vim.opt.smartindent = true
vim.opt.autoindent = true
vim.opt.smarttab = true
vim.opt.wrap = false
vim.opt.hlsearch = false
vim.opt.incsearch = true
vim.opt.termguicolors = true
vim.opt.scrolloff = 10
vim.opt.updatetime = 50
vim.opt.completeopt = { 'menu', 'menuone', 'noselect' }
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1
